#!/usr/bin/env bash

set -e

bench() {
  (
    cd "$1" || return
    go test -bench=. -benchtime=1000000x
  )
}

for t in singlechan dualchan; do
  echo "Running benchmark test for $t"
  echo "---------------------------------"
  bench $t
  echo ""
done
